sonar.projectKey=gitanilhn_Healthcare_Premium_Prediction

sonar.organization=gitanilhn

sonar.projectName=Healthcare_Premium_Project

sonar.sources=src

sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**