apiVersion: v1
kind: Service

metadata:
  name: healthcare-premium-api
  namespace: healthcare-premium
  labels:
    app: healthcare-premium-api
    app.kubernetes.io/instance: healthcare-premium-api
    app.kubernetes.io/name: healthcare-premium-api

spec:
  type: LoadBalancer

  selector:
    app: healthcare-premium-api

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000