name: Upload Artifacts to S3

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME: healthcare-premium-mlops-anil   # Change if different
  AWS_REGION: ap-south-1

permissions:
  id-token: write
  contents: read

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: List S3 Bucket
        run: aws s3 ls s3://${{ env.BUCKET_NAME }}

      - name: Upload Artifacts
        run: |
          aws s3 sync artifacts/ s3://${{ env.BUCKET_NAME }}/artifacts/
